version: 3.2

services:

  mongo:
    image: 'mongo'
    ports:
      - 27017:27017

  cassandra:
    image: 'cassandra:latest'
    ports:
      - 9042:9042

  neo4j:
    image: 'neo4j:3.5'
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=none

  movies-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
      - cassandra
      - neo4j